#!/bin/bash

if [ "$JMXTRANS_AGENT_ENABLED" == "true" ] ; then
  JAVA_ADDITIONAL="$JAVA_ADDITIONAL -javaagent:/opt/jmxtrans-agent.jar=/data/app/conf/jmxtrans-agent.xml"
  JAVA_ADDITIONAL="$JAVA_ADDITIONAL -Dgraphite.host=${GRAPHITE_HOSTNAME}"
  JAVA_ADDITIONAL="$JAVA_ADDITIONAL -Dgraphite.port=${GRAPHITE_PORT}"
  JAVA_ADDITIONAL="$JAVA_ADDITIONAL -Dgraphite.namePrefix=${GRAPHITE_NAME_PREFIX}"
fi

JAVA_ADDITIONAL="$JAVA_ADDITIONAL $JAVA_ADDITIONAL_1"
JAVA_ADDITIONAL="$JAVA_ADDITIONAL $JAVA_ADDITIONAL_2"
JAVA_ADDITIONAL="$JAVA_ADDITIONAL $JAVA_ADDITIONAL_3"
JAVA_ADDITIONAL="$JAVA_ADDITIONAL $JAVA_ADDITIONAL_4"
JAVA_ADDITIONAL="$JAVA_ADDITIONAL $JAVA_ADDITIONAL_5"
JAVA_ADDITIONAL="$JAVA_ADDITIONAL $JAVA_ADDITIONAL_6"
JAVA_ADDITIONAL="$JAVA_ADDITIONAL $JAVA_ADDITIONAL_7"
JAVA_ADDITIONAL="$JAVA_ADDITIONAL $JAVA_ADDITIONAL_8"
JAVA_ADDITIONAL="$JAVA_ADDITIONAL $JAVA_ADDITIONAL_9"

echo /usr/bin/java -Xmx${JAVA_MAX_HEAP} $JAVA_DEFAULT_OPTS $JAVA_ADDITIONAL $JAVA_OPTS -jar current/*.jar $@
/usr/bin/java -Xmx${JAVA_MAX_HEAP} $JAVA_DEFAULT_OPTS $JAVA_ADDITIONAL $JAVA_OPTS -jar current/*.jar $@
