---
- hosts: localhost
  connection: local
  tasks:
    - include_tasks: get-resource.yml
      loop: "{{ resources }}"
      loop_control:
        loop_var: resource
  vars:
    compress_command: gzip
    uncompress_command: gunzip
