def images 
  [
    {directory: 'docker-openjdk11', name: 'openjdk11'},
    {directory: 'docker-jmxtrans-agent', name: 'jmxtrans-agent'},
    {directory: 'docker-tomcat9', name: 'tomcat9'},
    {directory: 'docker-service-wrapper', name: 'service-wrapper'},
    {directory: 'docker-nodejs', name: 'nodejs'},
    {directory: 'docker-nodejs-build', name: 'nodejs-build'},
    {directory: 'docker-ruby', name: 'ruby'},
    {directory: 'docker-solr', name: 'solr'},
    {directory: 'docker-jar', name: 'jar'},
    {directory: 'docker-influxdb', name: 'influxdb'},
    {directory: 'docker-vault', name: 'vault'},
    {directory: 'docker-rabbitmq', name: 'rabbitmq'},
    {directory: 'docker-mailslurper', name: 'mailslurper'},
    {directory: 'docker-postgresql', name: 'postgresql'},
    {directory: 'docker-postgresql-client', name: 'postgresql-client'},
    {directory: 'docker-memcached', name: 'memcached'},
    {directory: 'docker-busybox', name: 'busybox'},
    {directory: 'docker-easy-rsa', name: 'easy-rsa'},
    {directory: 'docker-mariadb', name: 'mariadb'},
    {directory: 'docker-restic', name: 'restic'},
    {directory: 'docker-openjfx', name: 'openjfx'},
    {directory: 'docker-gradle', name: 'gradle'},
    {directory: 'docker-gradle', name: 'gradle-openjfx', parameter: "variant=openjfx"},
    {directory: 'docker-maven', name: 'maven'},
    {directory: 'docker-maven', name: 'maven-openjfx', parameter: "variant=openjfx"},
    {directory: 'docker-knot-resolver', name: 'knot-resolver'},
  ]
end
