require_relative '../rake/helper'

image :maven do
  @distribution = ENV["distribution"] || "buster"
  @variant = ENV["variant"] || @variant || "openjdk11"

  if @variant != "openjdk11"
    @container_build_args = "#{@container_build_args} --build-arg VARIANT=#{@variant}"
    @name = @name.to_s + "-" + @variant
  end
end
