require_relative '../rake/helper'

image :create_base_image do
  Rake::Task[:default].clear
  task default: [:build]

  Rake::Task[:build].clear
  task :build do

    ansible_playbook_args = "-e local_repository=#{@local_repository} -e remote_repository=#{@remote_repository} -e type=#{@type} -e distribution=#{@distribution} -e force=true"
    if @backend
      ansible_playbook_args = "-e backend=#{@backend.to_s} #{ansible_playbook_args}"
    end

    sh "sudo ansible-playbook create_base_image.yml #{@ansible_playbook_common_args} #{ansible_playbook_args}"
  end
end
