require_relative '../rake/helper'

image :create_base_image do
  Rake::Task[:default].clear
  task default: [:build]

  Rake::Task[:build].clear
  task :build do

    ansible_playbook_args = "-e local_repository=#{@local_repository} -e remote_repository=#{@remote_repository} -e type=#{@type} -e distribution=#{@distribution} -e force=true"
    ansible_command = "ansible-playbook"
    if @backend
      ansible_playbook_args = "-e backend=#{@backend.to_s} #{ansible_playbook_args}"
    end

    if not @buildah_type == :rootless
      ansible_command = "sudo ansible-playbook"
    else
      ansible_playbook_args += " -e buildah_type=rootless"
    end

    sh "#{ansible_command} create_base_image.yml #{@ansible_playbook_common_args} #{ansible_playbook_args}"
  end
end
