---
- hosts: localhost
  connection: local
  tasks:
    - name: include variables
      include_vars: vars.yml
    - name: download jmxtrans-agent
      get_url:
        url: "https://github.com/jmxtrans/jmxtrans-agent/releases/download/jmxtrans-agent-{{ jmxtrans_agent_version }}/jmxtrans-agent-{{ jmxtrans_agent_version }}.jar"
        dest: ./jmxtrans-agent.jar
        checksum: "sha256:{{ jmxtrans_agent_source_sha256 }}"
